// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Upaffe.Infrastructure.Persistence;

#nullable disable

namespace Upaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UpaffeDbContext))]
    [Migration("20260919124117_AddNotificationDeliveries")]
    partial class AddNotificationDeliveries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Upaffe.Domain.Access.BootstrapGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("armed_at");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_bootstrap_grant");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("bootstrap_singleton");

                    b.ToTable("bootstrap_grant", null, t =>
                        {
                            t.HasCheckConstraint("ck_bootstrap_consumed", "consumed_at is null or consumed_at >= armed_at");

                            t.HasCheckConstraint("ck_bootstrap_expiry", "expires_at > armed_at");

                            t.HasCheckConstraint("ck_bootstrap_hash", "octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_bootstrap_singleton", "is_singleton = true");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.BrowserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_browser_session");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("browser_session_operator");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("browser_session_secret_hash");

                    b.ToTable("browser_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_browser_session_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_browser_session_hash", "octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_browser_session_last_used", "last_used_at >= created_at and last_used_at <= expires_at");

                            t.HasCheckConstraint("ck_browser_session_revoked", "revoked_at is null or revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.HasKey("Id")
                        .HasName("pk_management_credential");

                    b.HasIndex("OperatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("management_credential_operator_name");

                    b.ToTable("management_credential", null, t =>
                        {
                            t.HasCheckConstraint("ck_management_credential_revoked", "revoked_at is null or revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredentialSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_management_credential_secret");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("management_credential_current_secret")
                        .HasFilter("expires_at is null");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("management_credential_secret_hash");

                    b.ToTable("management_credential_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_management_credential_secret_expiry", "expires_at is null or expires_at > created_at");

                            t.HasCheckConstraint("ck_management_credential_secret_hash", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_operator_identity");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("operator_singleton");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("operator_normalized_email");

                    b.ToTable("operator_identity", null, t =>
                        {
                            t.HasCheckConstraint("ck_operator_singleton", "is_singleton = true");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("EffectiveUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("effective_url");

                    b.Property<long>("EvaluationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("evaluation_generation");

                    b.Property<int>("ExecutionAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("execution_attempts");

                    b.Property<Guid?>("ExecutionLeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_lease_token");

                    b.Property<DateTimeOffset?>("ExecutionLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_lease_until");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("LastExecutionAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_execution_attempt_at");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<int?>("ResponseTimeMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_milliseconds");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_http_check");

                    b.HasIndex("ExecutionLeaseUntil")
                        .HasDatabaseName("http_check_expired_lease")
                        .HasFilter("trigger = 'Scheduled' and completed_at is null");

                    b.HasIndex("MonitorId", "CompletedAt")
                        .HasDatabaseName("http_check_monitor_completed");

                    b.HasIndex("MonitorId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("http_check_monitor_sequence");

                    b.ToTable("http_check", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_check_effective_url", "effective_url is null or (char_length(effective_url) between 1 and 2048 and effective_url !~ '[?#]')");

                            t.HasCheckConstraint("ck_http_check_execution_lease", "(trigger = 'Requested' and execution_lease_token is null and execution_lease_until is null and execution_attempts = 0 and last_execution_attempt_at is null) or (trigger = 'Scheduled' and execution_lease_token is not null and execution_lease_until > last_execution_attempt_at and execution_attempts > 0 and last_execution_attempt_at >= started_at)");

                            t.HasCheckConstraint("ck_http_check_generation", "evaluation_generation > 0");

                            t.HasCheckConstraint("ck_http_check_outcome", "outcome is null or outcome in ('Success', 'Failure')");

                            t.HasCheckConstraint("ck_http_check_reason", "failure_reason is null or failure_reason ~ '^[a-z][a-z0-9_]{0,63}$'");

                            t.HasCheckConstraint("ck_http_check_response_time", "response_time_milliseconds is null or response_time_milliseconds >= 0");

                            t.HasCheckConstraint("ck_http_check_result", "(outcome is null and completed_at is null and failure_reason is null and status_code is null and response_time_milliseconds is null and effective_url is null) or (outcome = 'Success' and completed_at >= started_at and failure_reason is null and status_code is not null and response_time_milliseconds is not null and effective_url is not null) or (outcome = 'Failure' and completed_at >= started_at and failure_reason is not null)");

                            t.HasCheckConstraint("ck_http_check_sequence", "sequence > 0");

                            t.HasCheckConstraint("ck_http_check_started", "started_at >= scheduled_for");

                            t.HasCheckConstraint("ck_http_check_status", "status_code is null or status_code between 100 and 599");

                            t.HasCheckConstraint("ck_http_check_trigger", "trigger in ('Scheduled', 'Requested')");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("EvaluationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("evaluation_generation");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("expected_status_code");

                    b.Property<Guid?>("FailureStreakStartId")
                        .HasColumnType("uuid")
                        .HasColumnName("failure_streak_start_id");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("failure_threshold");

                    b.Property<bool>("HasTargetQuery")
                        .HasColumnType("boolean")
                        .HasColumnName("has_target_query");

                    b.Property<string>("Instruction")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instruction");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<long>("LastAppliedSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_applied_sequence");

                    b.Property<Guid?>("LatestResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_result_id");

                    b.Property<Guid?>("LatestSuccessId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_success_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_check_at");

                    b.Property<long>("NextSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_sequence");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RunbookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("runbook_url");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_url");

                    b.Property<string>("TextCondition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("text_condition");

                    b.Property<string>("TextFragment")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("text_fragment");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_http_monitor");

                    b.HasIndex("FailureStreakStartId")
                        .HasDatabaseName("http_monitor_failure_streak_start");

                    b.HasIndex("LatestResultId");

                    b.HasIndex("LatestSuccessId");

                    b.HasIndex("NextCheckAt")
                        .HasDatabaseName("http_monitor_due")
                        .HasFilter("deleted_at is null and state <> 'Paused'");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique()
                        .HasDatabaseName("http_monitor_project_key");

                    b.ToTable("http_monitor", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_deleted", "deleted_at is null or (deleted_at >= created_at and next_check_at is null)");

                            t.HasCheckConstraint("ck_http_monitor_expected_status", "expected_status_code between 100 and 599");

                            t.HasCheckConstraint("ck_http_monitor_failures", "(consecutive_failures = 0 and failure_streak_start_id is null) or (consecutive_failures > 0 and failure_streak_start_id is not null)");

                            t.HasCheckConstraint("ck_http_monitor_generation", "evaluation_generation > 0");

                            t.HasCheckConstraint("ck_http_monitor_interval", "interval_seconds between 30 and 2592000");

                            t.HasCheckConstraint("ck_http_monitor_key", "key ~ '^[a-z][a-z0-9-]{1,39}$'");

                            t.HasCheckConstraint("ck_http_monitor_latest", "latest_success_id is null or latest_result_id is not null");

                            t.HasCheckConstraint("ck_http_monitor_name", "char_length(btrim(name)) between 1 and 100");

                            t.HasCheckConstraint("ck_http_monitor_pause", "(state = 'Paused' and paused_at is not null and next_check_at is null) or (state <> 'Paused' and paused_at is null and (deleted_at is not null or next_check_at is not null))");

                            t.HasCheckConstraint("ck_http_monitor_sequence", "next_sequence > 0 and last_applied_sequence >= 0 and last_applied_sequence < next_sequence");

                            t.HasCheckConstraint("ck_http_monitor_state", "state in ('Untested', 'Healthy', 'Failing', 'Paused')");

                            t.HasCheckConstraint("ck_http_monitor_target", "char_length(target_url) between 1 and 2048 and target_url !~ '[?#]'");

                            t.HasCheckConstraint("ck_http_monitor_text", "(text_condition = 'None' and text_fragment is null) or (text_condition in ('Required', 'Forbidden') and char_length(text_fragment) between 1 and 4096)");

                            t.HasCheckConstraint("ck_http_monitor_threshold", "failure_threshold between 1 and 100");

                            t.HasCheckConstraint("ck_http_monitor_timeout", "timeout_seconds between 1 and 60 and timeout_seconds <= interval_seconds");

                            t.HasCheckConstraint("ck_http_monitor_updated", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_http_monitor_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_http_monitor_header");

                    b.HasIndex("MonitorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("http_monitor_header_monitor_name");

                    b.ToTable("http_monitor_header", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_header_managed", "name not in ('connection', 'content-length', 'host', 'keep-alive', 'proxy-authenticate', 'proxy-authorization', 'te', 'trailer', 'transfer-encoding', 'upgrade')");

                            t.HasCheckConstraint("ck_http_monitor_header_name", "name ~ '^[!#$%&''*+.^_`|~0-9a-z-]{1,128}$'");

                            t.HasCheckConstraint("ck_http_monitor_header_updated", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeaderSecret", b =>
                {
                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("header_id");

                    b.Property<byte[]>("ValueUtf8")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_utf8");

                    b.HasKey("HeaderId")
                        .HasName("pk_http_monitor_header_secret");

                    b.ToTable("http_monitor_header_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_header_secret_value", "octet_length(value_utf8) <= 4096");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorSecret", b =>
                {
                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<byte[]>("TargetQueryUtf8")
                        .HasColumnType("bytea")
                        .HasColumnName("target_query_utf8");

                    b.HasKey("MonitorId")
                        .HasName("pk_http_monitor_secret");

                    b.ToTable("http_monitor_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_secret_query", "target_query_utf8 is null or (octet_length(target_query_utf8) between 1 and 8192 and get_byte(target_query_utf8, 0) = 63)");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BeganAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("began_at");

                    b.Property<Guid>("FirstFailureCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_failure_check_id");

                    b.Property<long>("FirstFailureSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("first_failure_sequence");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<Guid>("LatestFailureCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_failure_check_id");

                    b.Property<long>("LatestFailureSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_failure_sequence");

                    b.Property<string>("LatestReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("latest_reason");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpeningCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("opening_check_id");

                    b.Property<long>("OpeningSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_sequence");

                    b.Property<string>("OriginalReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("original_reason");

                    b.Property<Guid?>("ResolutionCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolution_check_id");

                    b.Property<long?>("ResolutionSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("resolution_sequence");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_incident");

                    b.HasIndex("FirstFailureCheckId");

                    b.HasIndex("LatestFailureCheckId");

                    b.HasIndex("MonitorId")
                        .IsUnique()
                        .HasDatabaseName("incident_one_open_per_monitor")
                        .HasFilter("resolved_at is null");

                    b.HasIndex("OpeningCheckId");

                    b.HasIndex("ResolutionCheckId");

                    b.HasIndex("MonitorId", "OpenedAt")
                        .HasDatabaseName("incident_monitor_opened");

                    b.ToTable("incident", null, t =>
                        {
                            t.HasCheckConstraint("ck_incident_latest_reason", "latest_reason ~ '^[a-z][a-z0-9_]{0,63}$'");

                            t.HasCheckConstraint("ck_incident_original_reason", "original_reason ~ '^[a-z][a-z0-9_]{0,63}$'");

                            t.HasCheckConstraint("ck_incident_resolution", "(resolved_at is null and resolution_check_id is null and resolution_sequence is null) or (resolved_at >= last_observed_at and resolution_check_id is not null and resolution_sequence > latest_failure_sequence)");

                            t.HasCheckConstraint("ck_incident_sequences", "first_failure_sequence > 0 and opening_sequence >= first_failure_sequence and latest_failure_sequence >= opening_sequence");

                            t.HasCheckConstraint("ck_incident_times", "began_at <= opened_at and began_at <= last_observed_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.PushIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BeganAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("began_at");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<Guid>("LatestFailureReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_failure_report_id");

                    b.Property<long>("LatestFailureSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_failure_sequence");

                    b.Property<string>("LatestReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("latest_reason");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpeningReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("opening_report_id");

                    b.Property<long>("OpeningSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_sequence");

                    b.Property<string>("OriginalReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("original_reason");

                    b.Property<Guid?>("ResolutionReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolution_report_id");

                    b.Property<long?>("ResolutionSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("resolution_sequence");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_push_incident");

                    b.HasIndex("LatestFailureReportId");

                    b.HasIndex("MonitorId")
                        .IsUnique()
                        .HasDatabaseName("push_incident_one_open_per_monitor")
                        .HasFilter("resolved_at is null");

                    b.HasIndex("OpeningReportId");

                    b.HasIndex("ResolutionReportId");

                    b.HasIndex("MonitorId", "OpenedAt")
                        .HasDatabaseName("push_incident_monitor_opened");

                    b.ToTable("push_incident", null, t =>
                        {
                            t.HasCheckConstraint("ck_push_incident_latest_reason", "latest_reason in ('reported_failure', 'report_missing')");

                            t.HasCheckConstraint("ck_push_incident_original_reason", "original_reason in ('reported_failure', 'report_missing')");

                            t.HasCheckConstraint("ck_push_incident_resolution", "(resolved_at is null and resolution_report_id is null and resolution_sequence is null) or (resolved_at is not null and resolution_report_id is not null and resolution_sequence > latest_failure_sequence)");

                            t.HasCheckConstraint("ck_push_incident_sequences", "opening_sequence > 0 and latest_failure_sequence >= opening_sequence");

                            t.HasCheckConstraint("ck_push_incident_times", "began_at <= opened_at + interval '5 minutes' and began_at <= last_observed_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.PushMonitor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeadlineLeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("deadline_lease_token");

                    b.Property<DateTimeOffset?>("DeadlineLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_lease_until");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("EvaluationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("evaluation_generation");

                    b.Property<string>("Instruction")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instruction");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("LastAppliedObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_applied_observed_at");

                    b.Property<long>("LastAppliedSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_applied_sequence");

                    b.Property<DateTimeOffset?>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at");

                    b.Property<Guid?>("LatestReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_report_id");

                    b.Property<Guid?>("LatestSuccessId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_success_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_deadline_at");

                    b.Property<long>("NextSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_sequence");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RunbookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("runbook_url");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<int>("ToleranceSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("tolerance_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_push_monitor");

                    b.HasIndex("DeadlineLeaseUntil")
                        .HasDatabaseName("push_monitor_deadline_lease")
                        .HasFilter("deadline_lease_until is not null");

                    b.HasIndex("LatestReportId");

                    b.HasIndex("LatestSuccessId");

                    b.HasIndex("NextDeadlineAt")
                        .HasDatabaseName("push_monitor_due")
                        .HasFilter("deleted_at is null and state <> 'Paused'");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique()
                        .HasDatabaseName("push_monitor_project_key");

                    b.ToTable("push_monitor", null, t =>
                        {
                            t.HasCheckConstraint("ck_push_monitor_applied", "(last_applied_sequence = 0 and last_applied_observed_at is null) or (last_applied_sequence > 0 and last_applied_observed_at is not null)");

                            t.HasCheckConstraint("ck_push_monitor_deadline_lease", "(deadline_lease_token is null and deadline_lease_until is null) or (deadline_lease_token is not null and deadline_lease_until is not null)");

                            t.HasCheckConstraint("ck_push_monitor_deleted", "deleted_at is null or (deleted_at >= created_at and next_deadline_at is null)");

                            t.HasCheckConstraint("ck_push_monitor_generation", "evaluation_generation > 0");

                            t.HasCheckConstraint("ck_push_monitor_interval", "interval_seconds between 30 and 31536000");

                            t.HasCheckConstraint("ck_push_monitor_key", "key ~ '^[a-z][a-z0-9-]{1,39}$'");

                            t.HasCheckConstraint("ck_push_monitor_latest", "latest_success_id is null or latest_report_id is not null");

                            t.HasCheckConstraint("ck_push_monitor_mode", "mode in ('JobCompletion', 'StateReport')");

                            t.HasCheckConstraint("ck_push_monitor_name", "char_length(btrim(name)) between 1 and 100");

                            t.HasCheckConstraint("ck_push_monitor_pause", "(state = 'Paused' and paused_at is not null and next_deadline_at is null) or (state <> 'Paused' and paused_at is null and (deleted_at is not null or next_deadline_at is not null))");

                            t.HasCheckConstraint("ck_push_monitor_receipt", "last_received_at is null or latest_report_id is not null");

                            t.HasCheckConstraint("ck_push_monitor_sequence", "next_sequence > 0 and last_applied_sequence >= 0 and last_applied_sequence < next_sequence");

                            t.HasCheckConstraint("ck_push_monitor_state", "state in ('Untested', 'Healthy', 'Failing', 'Paused')");

                            t.HasCheckConstraint("ck_push_monitor_tolerance", "tolerance_seconds between 0 and 2592000 and tolerance_seconds <= interval_seconds");

                            t.HasCheckConstraint("ck_push_monitor_updated", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_push_monitor_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.PushReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Applicable")
                        .HasColumnType("boolean")
                        .HasColumnName("applicable");

                    b.Property<string>("DiagnosticReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("diagnostic_reason");

                    b.Property<long>("EvaluationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("evaluation_generation");

                    b.Property<bool>("IsDeadlineObservation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deadline_observation");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_push_report");

                    b.HasIndex("MonitorId", "ReceivedAt")
                        .HasDatabaseName("push_report_monitor_received");

                    b.HasIndex("MonitorId", "ReportId")
                        .IsUnique()
                        .HasDatabaseName("push_report_monitor_report_id");

                    b.HasIndex("MonitorId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("push_report_monitor_sequence");

                    b.HasIndex("MonitorId", "EvaluationGeneration", "ObservedAt")
                        .IsUnique()
                        .HasDatabaseName("push_report_one_deadline_observation")
                        .HasFilter("is_deadline_observation");

                    b.ToTable("push_report", null, t =>
                        {
                            t.HasCheckConstraint("ck_push_report_deadline", "(not is_deadline_observation) or (outcome = 'Failure' and diagnostic_reason = 'report_missing')");

                            t.HasCheckConstraint("ck_push_report_diagnostic", "(outcome = 'Success' and diagnostic_reason is null) or outcome = 'Failure'");

                            t.HasCheckConstraint("ck_push_report_generation", "evaluation_generation > 0");

                            t.HasCheckConstraint("ck_push_report_outcome", "outcome in ('Success', 'Failure')");

                            t.HasCheckConstraint("ck_push_report_sequence", "sequence > 0");

                            t.HasCheckConstraint("ck_push_report_time", "(is_deadline_observation and observed_at <= received_at) or (not is_deadline_observation and observed_at <= received_at + interval '5 minutes' and observed_at >= received_at - interval '90 days')");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.ReportingCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.HasKey("Id")
                        .HasName("pk_reporting_credential");

                    b.HasIndex("MonitorId")
                        .IsUnique()
                        .HasDatabaseName("reporting_credential_monitor");

                    b.ToTable("reporting_credential", null, t =>
                        {
                            t.HasCheckConstraint("ck_reporting_credential_revoked", "revoked_at is null or revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.ReportingCredentialSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_reporting_credential_secret");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("reporting_credential_current_secret")
                        .HasFilter("expires_at is null");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("reporting_credential_secret_hash");

                    b.ToTable("reporting_credential_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_reporting_credential_secret_expiry", "expires_at is null or expires_at > created_at");

                            t.HasCheckConstraint("ck_reporting_credential_secret_hash", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Notifications.EmailConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("DefaultRecipients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("default_recipients");

                    b.Property<string>("Host")
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int?>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("PublicBaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("public_base_url");

                    b.Property<string>("Security")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security");

                    b.Property<string>("SenderAddress")
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("SenderName")
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_email_configuration");

                    b.ToTable("email_configuration", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_configuration_port", "port is null or port between 1 and 65535");

                            t.HasCheckConstraint("ck_email_configuration_security", "security in ('none', 'starttls', 'tls')");

                            t.HasCheckConstraint("ck_email_configuration_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Notifications.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("MonitorKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("monitor_key");

                    b.Property<string>("MonitorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("monitor_name");

                    b.Property<string>("MonitorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("monitor_type");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_key");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_name");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<string>("RecipientKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_key");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_delivery");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("notification_delivery_due");

                    b.HasIndex("IncidentId", "Kind", "RecipientKey")
                        .IsUnique()
                        .HasDatabaseName("notification_delivery_identity");

                    b.ToTable("notification_delivery", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_attempts", "attempt_count between 0 and 5");

                            t.HasCheckConstraint("ck_notification_kind", "kind in ('Alert', 'Recovery')");

                            t.HasCheckConstraint("ck_notification_monitor_type", "monitor_type in ('http', 'push')");

                            t.HasCheckConstraint("ck_notification_state", "state in ('Queued', 'Claimed', 'Retrying', 'Accepted', 'TerminalFailure', 'Obsolete')");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("Recipients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recipients");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("project_key");

                    b.ToTable("project", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_deleted", "deleted_at is null or deleted_at >= created_at");

                            t.HasCheckConstraint("ck_project_key", "key ~ '^[a-z][a-z0-9-]{1,39}$'");

                            t.HasCheckConstraint("ck_project_name", "char_length(btrim(name)) between 1 and 100");

                            t.HasCheckConstraint("ck_project_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.BrowserSession", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_browser_session_operator");
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredential", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_credential_operator");
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredentialSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.ManagementCredential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_credential_secret");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpCheck", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_http_check_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitor", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("FailureStreakStartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_http_monitor_failure_streak_start");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("LatestResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_http_monitor_latest_result");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("LatestSuccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_http_monitor_latest_success");

                    b.HasOne("Upaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_project");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeader", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_header_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeaderSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitorHeader", null)
                        .WithOne()
                        .HasForeignKey("Upaffe.Domain.Monitoring.HttpMonitorHeaderSecret", "HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_header_secret_header");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithOne()
                        .HasForeignKey("Upaffe.Domain.Monitoring.HttpMonitorSecret", "MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_secret_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.Incident", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("FirstFailureCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_first_failure");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("LatestFailureCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_latest_failure");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_monitor");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("OpeningCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_opening_check");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("ResolutionCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_resolution_check");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.PushIncident", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.PushReport", null)
                        .WithMany()
                        .HasForeignKey("LatestFailureReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_push_incident_latest_failure_report");

                    b.HasOne("Upaffe.Domain.Monitoring.PushMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_push_incident_monitor");

                    b.HasOne("Upaffe.Domain.Monitoring.PushReport", null)
                        .WithMany()
                        .HasForeignKey("OpeningReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_push_incident_opening_report");

                    b.HasOne("Upaffe.Domain.Monitoring.PushReport", null)
                        .WithMany()
                        .HasForeignKey("ResolutionReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_push_incident_resolution_report");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.PushMonitor", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.PushReport", null)
                        .WithMany()
                        .HasForeignKey("LatestReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_push_monitor_latest_report");

                    b.HasOne("Upaffe.Domain.Monitoring.PushReport", null)
                        .WithMany()
                        .HasForeignKey("LatestSuccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_push_monitor_latest_success");

                    b.HasOne("Upaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_push_monitor_project");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.PushReport", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.PushMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_push_report_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.ReportingCredential", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.PushMonitor", null)
                        .WithOne()
                        .HasForeignKey("Upaffe.Domain.Monitoring.ReportingCredential", "MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reporting_credential_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.ReportingCredentialSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.ReportingCredential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reporting_credential_secret");
                });
#pragma warning restore 612, 618
        }
    }
}
