// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Upaffe.Infrastructure.Persistence;

#nullable disable

namespace Upaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UpaffeDbContext))]
    [Migration("20260916164858_TheHttpMonitoringModel")]
    partial class TheHttpMonitoringModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Upaffe.Domain.Access.BootstrapGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("armed_at");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_bootstrap_grant");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("bootstrap_singleton");

                    b.ToTable("bootstrap_grant", null, t =>
                        {
                            t.HasCheckConstraint("ck_bootstrap_consumed", "consumed_at is null or consumed_at >= armed_at");

                            t.HasCheckConstraint("ck_bootstrap_expiry", "expires_at > armed_at");

                            t.HasCheckConstraint("ck_bootstrap_hash", "octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_bootstrap_singleton", "is_singleton = true");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.BrowserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_browser_session");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("browser_session_operator");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("browser_session_secret_hash");

                    b.ToTable("browser_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_browser_session_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_browser_session_hash", "octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_browser_session_last_used", "last_used_at >= created_at and last_used_at <= expires_at");

                            t.HasCheckConstraint("ck_browser_session_revoked", "revoked_at is null or revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.HasKey("Id")
                        .HasName("pk_management_credential");

                    b.HasIndex("OperatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("management_credential_operator_name");

                    b.ToTable("management_credential", null, t =>
                        {
                            t.HasCheckConstraint("ck_management_credential_revoked", "revoked_at is null or revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredentialSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_management_credential_secret");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("management_credential_current_secret")
                        .HasFilter("expires_at is null");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("management_credential_secret_hash");

                    b.ToTable("management_credential_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_management_credential_secret_expiry", "expires_at is null or expires_at > created_at");

                            t.HasCheckConstraint("ck_management_credential_secret_hash", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_operator_identity");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("operator_singleton");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("operator_normalized_email");

                    b.ToTable("operator_identity", null, t =>
                        {
                            t.HasCheckConstraint("ck_operator_singleton", "is_singleton = true");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("EffectiveUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("effective_url");

                    b.Property<long>("EvaluationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("evaluation_generation");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<int?>("ResponseTimeMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_milliseconds");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_http_check");

                    b.HasIndex("MonitorId", "CompletedAt")
                        .HasDatabaseName("http_check_monitor_completed");

                    b.HasIndex("MonitorId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("http_check_monitor_sequence");

                    b.ToTable("http_check", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_check_effective_url", "effective_url is null or (char_length(effective_url) between 1 and 2048 and effective_url !~ '[?#]')");

                            t.HasCheckConstraint("ck_http_check_generation", "evaluation_generation > 0");

                            t.HasCheckConstraint("ck_http_check_outcome", "outcome is null or outcome in ('Success', 'Failure')");

                            t.HasCheckConstraint("ck_http_check_reason", "failure_reason is null or failure_reason ~ '^[a-z][a-z0-9_]{0,63}$'");

                            t.HasCheckConstraint("ck_http_check_response_time", "response_time_milliseconds is null or response_time_milliseconds >= 0");

                            t.HasCheckConstraint("ck_http_check_result", "(outcome is null and completed_at is null and failure_reason is null and status_code is null and response_time_milliseconds is null and effective_url is null) or (outcome = 'Success' and completed_at >= started_at and failure_reason is null and status_code is not null and response_time_milliseconds is not null and effective_url is not null) or (outcome = 'Failure' and completed_at >= started_at and failure_reason is not null)");

                            t.HasCheckConstraint("ck_http_check_sequence", "sequence > 0");

                            t.HasCheckConstraint("ck_http_check_started", "started_at >= scheduled_for");

                            t.HasCheckConstraint("ck_http_check_status", "status_code is null or status_code between 100 and 599");

                            t.HasCheckConstraint("ck_http_check_trigger", "trigger in ('Scheduled', 'Requested')");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("EvaluationGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("evaluation_generation");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("expected_status_code");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("failure_threshold");

                    b.Property<bool>("HasTargetQuery")
                        .HasColumnType("boolean")
                        .HasColumnName("has_target_query");

                    b.Property<string>("Instruction")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instruction");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<long>("LastAppliedSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_applied_sequence");

                    b.Property<Guid?>("LatestResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_result_id");

                    b.Property<Guid?>("LatestSuccessId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_success_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_check_at");

                    b.Property<long>("NextSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_sequence");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RunbookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("runbook_url");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_url");

                    b.Property<string>("TextCondition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("text_condition");

                    b.Property<string>("TextFragment")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("text_fragment");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_http_monitor");

                    b.HasIndex("LatestResultId");

                    b.HasIndex("LatestSuccessId");

                    b.HasIndex("NextCheckAt")
                        .HasDatabaseName("http_monitor_due")
                        .HasFilter("deleted_at is null and state <> 'Paused'");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique()
                        .HasDatabaseName("http_monitor_project_key");

                    b.ToTable("http_monitor", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_deleted", "deleted_at is null or (deleted_at >= created_at and next_check_at is null)");

                            t.HasCheckConstraint("ck_http_monitor_expected_status", "expected_status_code between 100 and 599");

                            t.HasCheckConstraint("ck_http_monitor_failures", "consecutive_failures >= 0");

                            t.HasCheckConstraint("ck_http_monitor_generation", "evaluation_generation > 0");

                            t.HasCheckConstraint("ck_http_monitor_interval", "interval_seconds between 30 and 2592000");

                            t.HasCheckConstraint("ck_http_monitor_key", "key ~ '^[a-z][a-z0-9-]{1,39}$'");

                            t.HasCheckConstraint("ck_http_monitor_latest", "latest_success_id is null or latest_result_id is not null");

                            t.HasCheckConstraint("ck_http_monitor_name", "char_length(btrim(name)) between 1 and 100");

                            t.HasCheckConstraint("ck_http_monitor_pause", "(state = 'Paused' and paused_at is not null and next_check_at is null) or (state <> 'Paused' and paused_at is null and (deleted_at is not null or next_check_at is not null))");

                            t.HasCheckConstraint("ck_http_monitor_sequence", "next_sequence > 0 and last_applied_sequence >= 0 and last_applied_sequence < next_sequence");

                            t.HasCheckConstraint("ck_http_monitor_state", "state in ('Untested', 'Healthy', 'Failing', 'Paused')");

                            t.HasCheckConstraint("ck_http_monitor_target", "char_length(target_url) between 1 and 2048 and target_url !~ '[?#]'");

                            t.HasCheckConstraint("ck_http_monitor_text", "(text_condition = 'None' and text_fragment is null) or (text_condition in ('Required', 'Forbidden') and char_length(text_fragment) between 1 and 4096)");

                            t.HasCheckConstraint("ck_http_monitor_threshold", "failure_threshold between 1 and 100");

                            t.HasCheckConstraint("ck_http_monitor_timeout", "timeout_seconds between 1 and 60 and timeout_seconds <= interval_seconds");

                            t.HasCheckConstraint("ck_http_monitor_updated", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_http_monitor_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_http_monitor_header");

                    b.HasIndex("MonitorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("http_monitor_header_monitor_name");

                    b.ToTable("http_monitor_header", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_header_managed", "name not in ('connection', 'content-length', 'host', 'keep-alive', 'proxy-authenticate', 'proxy-authorization', 'te', 'trailer', 'transfer-encoding', 'upgrade')");

                            t.HasCheckConstraint("ck_http_monitor_header_name", "name ~ '^[!#$%&''*+.^_`|~0-9a-z-]{1,128}$'");

                            t.HasCheckConstraint("ck_http_monitor_header_updated", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeaderSecret", b =>
                {
                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("header_id");

                    b.Property<byte[]>("ValueUtf8")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_utf8");

                    b.HasKey("HeaderId")
                        .HasName("pk_http_monitor_header_secret");

                    b.ToTable("http_monitor_header_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_header_secret_value", "octet_length(value_utf8) <= 4096");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorSecret", b =>
                {
                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<byte[]>("TargetQueryUtf8")
                        .HasColumnType("bytea")
                        .HasColumnName("target_query_utf8");

                    b.HasKey("MonitorId")
                        .HasName("pk_http_monitor_secret");

                    b.ToTable("http_monitor_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_http_monitor_secret_query", "target_query_utf8 is null or (octet_length(target_query_utf8) between 1 and 8192 and get_byte(target_query_utf8, 0) = 63)");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BeganAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("began_at");

                    b.Property<Guid>("FirstFailureCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_failure_check_id");

                    b.Property<long>("FirstFailureSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("first_failure_sequence");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<Guid>("LatestFailureCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_failure_check_id");

                    b.Property<long>("LatestFailureSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_failure_sequence");

                    b.Property<string>("LatestReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("latest_reason");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpeningCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("opening_check_id");

                    b.Property<long>("OpeningSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_sequence");

                    b.Property<string>("OriginalReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("original_reason");

                    b.Property<Guid?>("ResolutionCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolution_check_id");

                    b.Property<long?>("ResolutionSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("resolution_sequence");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_incident");

                    b.HasIndex("FirstFailureCheckId");

                    b.HasIndex("LatestFailureCheckId");

                    b.HasIndex("MonitorId")
                        .IsUnique()
                        .HasDatabaseName("incident_one_open_per_monitor")
                        .HasFilter("resolved_at is null");

                    b.HasIndex("OpeningCheckId");

                    b.HasIndex("ResolutionCheckId");

                    b.HasIndex("MonitorId", "OpenedAt")
                        .HasDatabaseName("incident_monitor_opened");

                    b.ToTable("incident", null, t =>
                        {
                            t.HasCheckConstraint("ck_incident_latest_reason", "latest_reason ~ '^[a-z][a-z0-9_]{0,63}$'");

                            t.HasCheckConstraint("ck_incident_original_reason", "original_reason ~ '^[a-z][a-z0-9_]{0,63}$'");

                            t.HasCheckConstraint("ck_incident_resolution", "(resolved_at is null and resolution_check_id is null and resolution_sequence is null) or (resolved_at >= last_observed_at and resolution_check_id is not null and resolution_sequence > latest_failure_sequence)");

                            t.HasCheckConstraint("ck_incident_sequences", "first_failure_sequence > 0 and opening_sequence >= first_failure_sequence and latest_failure_sequence >= opening_sequence");

                            t.HasCheckConstraint("ck_incident_times", "began_at <= opened_at and began_at <= last_observed_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("project_key");

                    b.ToTable("project", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_deleted", "deleted_at is null or deleted_at >= created_at");

                            t.HasCheckConstraint("ck_project_key", "key ~ '^[a-z][a-z0-9-]{1,39}$'");

                            t.HasCheckConstraint("ck_project_name", "char_length(btrim(name)) between 1 and 100");

                            t.HasCheckConstraint("ck_project_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.BrowserSession", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_browser_session_operator");
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredential", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_credential_operator");
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredentialSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.ManagementCredential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_credential_secret");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpCheck", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_http_check_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitor", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("LatestResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_http_monitor_latest_result");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("LatestSuccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_http_monitor_latest_success");

                    b.HasOne("Upaffe.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_project");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeader", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_header_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorHeaderSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitorHeader", null)
                        .WithOne()
                        .HasForeignKey("Upaffe.Domain.Monitoring.HttpMonitorHeaderSecret", "HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_header_secret_header");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.HttpMonitorSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithOne()
                        .HasForeignKey("Upaffe.Domain.Monitoring.HttpMonitorSecret", "MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_http_monitor_secret_monitor");
                });

            modelBuilder.Entity("Upaffe.Domain.Monitoring.Incident", b =>
                {
                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("FirstFailureCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_first_failure");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("LatestFailureCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_latest_failure");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_monitor");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("OpeningCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_opening_check");

                    b.HasOne("Upaffe.Domain.Monitoring.HttpCheck", null)
                        .WithMany()
                        .HasForeignKey("ResolutionCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_resolution_check");
                });
#pragma warning restore 612, 618
        }
    }
}
