// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Upaffe.Infrastructure.Persistence;

#nullable disable

namespace Upaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UpaffeDbContext))]
    [Migration("20260916142414_TheAccessAndProjectModel")]
    partial class TheAccessAndProjectModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Upaffe.Domain.Access.BootstrapGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("armed_at");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_bootstrap_grant");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("bootstrap_singleton");

                    b.ToTable("bootstrap_grant", null, t =>
                        {
                            t.HasCheckConstraint("ck_bootstrap_consumed", "consumed_at is null or consumed_at >= armed_at");

                            t.HasCheckConstraint("ck_bootstrap_expiry", "expires_at > armed_at");

                            t.HasCheckConstraint("ck_bootstrap_hash", "octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_bootstrap_singleton", "is_singleton = true");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.BrowserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_browser_session");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("browser_session_operator");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("browser_session_secret_hash");

                    b.ToTable("browser_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_browser_session_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_browser_session_hash", "octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_browser_session_last_used", "last_used_at >= created_at and last_used_at <= expires_at");

                            t.HasCheckConstraint("ck_browser_session_revoked", "revoked_at is null or revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.HasKey("Id")
                        .HasName("pk_management_credential");

                    b.HasIndex("OperatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("management_credential_operator_name");

                    b.ToTable("management_credential", null, t =>
                        {
                            t.HasCheckConstraint("ck_management_credential_revoked", "revoked_at is null or revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredentialSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_management_credential_secret");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("management_credential_current_secret")
                        .HasFilter("expires_at is null");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("management_credential_secret_hash");

                    b.ToTable("management_credential_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_management_credential_secret_expiry", "expires_at is null or expires_at > created_at");

                            t.HasCheckConstraint("ck_management_credential_secret_hash", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_operator_identity");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("operator_singleton");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("operator_normalized_email");

                    b.ToTable("operator_identity", null, t =>
                        {
                            t.HasCheckConstraint("ck_operator_singleton", "is_singleton = true");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("project_key");

                    b.ToTable("project", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_deleted", "deleted_at is null or deleted_at >= created_at");

                            t.HasCheckConstraint("ck_project_key", "key ~ '^[a-z][a-z0-9-]{1,39}$'");

                            t.HasCheckConstraint("ck_project_name", "char_length(btrim(name)) between 1 and 100");

                            t.HasCheckConstraint("ck_project_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Upaffe.Domain.Access.BrowserSession", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_browser_session_operator");
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredential", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_credential_operator");
                });

            modelBuilder.Entity("Upaffe.Domain.Access.ManagementCredentialSecret", b =>
                {
                    b.HasOne("Upaffe.Domain.Access.ManagementCredential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_credential_secret");
                });
#pragma warning restore 612, 618
        }
    }
}
